### ISSUE TITLE
Support for MediaTek

### ISSUE THREAD

**Issue by ketan-jainn** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#320]
I have a laptop Asus Tuf F15 which comes with MediaTek MT7921. Please add support for MediaTek as well.

**Comment by chris1111** [comment]
MediaTek MT7921 is not support [in macOS](https://github.com/chris1111/D-LinkUtility-Package)

The WiFi/BT Card needs to be replaced with a [BCM94352Z](https://www.aliexpress.com/item/4001019134803.html?src=google&src=google&albch=shopping&acnt=272-267-0231&slnk=&plac=&mtctp=&albbt=Google_7_shopping&gclsrc=aw.ds&albagn=888888&ds_e_adid=&ds_e_matchtype=&ds_e_device=c&ds_e_network=x&ds_e_product_group_id=&ds_e_product_id=en4001019134803&ds_e_product_merchant_id=109161313&ds_e_product_country=CA&ds_e_product_language=en&ds_e_product_channel=online&ds_e_product_store_id=&ds_url_v=2&albcp=20695954287&albag=&isSmbAutoCall=false&needSmbHouyi=false&gad_source=1&gclid=Cj0KCQiAv8SsBhC7ARIsALIkVT1oG86TLMkIuJCnw3Ecnu3XUINNYO7QUSoEyPIRq9-f1RkrYeE_ze0aApE6EALw_wcB&aff_fcid=6e6e0005cfd44d1d9a2109a8b403c1bf-1704037467771-07120-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=6e6e0005cfd44d1d9a2109a8b403c1bf-1704037467771-07120-UneMJZVf&terminal_id=3c3f329a1391442b92945285fdd8be73&afSmartRedirect=y) in order to have FULL Native Wirelless Features.
